blueprint:
  name: Eglo/AwoX Remote 3-Bank Control (ZHA)
  description: |
    Control any Home Assistant lights or devices with the Eglo/AwoX ERCU_3groups_Zm remote using its 3-bank functionality.
    
    **Simple Setup:**
    1. Install the quirk (eglo_ercu_awox_3banks.py)
    2. Pair the remote with ZHA
    3. Select this blueprint and choose your devices for each bank
    4. Done! Press buttons 1/2/3 on the remote to switch banks
    
    **No Touchlink or ZHA groups needed!** The blueprint handles everything in Home Assistant.
    
    **Features:**
    - 3 independent banks (switch with buttons 1, 2, 3 on remote)
    - Control ANY Home Assistant lights, switches, or devices
    - All 13 control buttons (ON/OFF, colors, brightness, temperature, scenes, refresh)
    - Short and long press actions
    - Fully customizable per bank
    
  domain: automation
  input:
    remote:
      name: Eglo/AwoX Remote
      description: The Eglo/AwoX ERCU_3groups_Zm remote to use
      selector:
        device:
          integration: zha
          manufacturer: AwoX
          model: ERCU_3groups_Zm
          multiple: false
    
    bank:
      name: Bank Number
      description: |
        Which bank to control (1, 2, or 3).
        Create 3 separate automations (one for each bank) to use all banks.
        Press button 1/2/3 on the remote to switch between banks.
      selector:
        select:
          options:
            - label: "Bank 1"
              value: "1"
            - label: "Bank 2"
              value: "2"
            - label: "Bank 3"
              value: "3"
      default: "1"
    
    target_lights:
      name: Target Devices
      description: |
        Select ANY lights, switches, or devices to control with this bank.
        You can mix different device types!
      selector:
        target:
          entity:
            - domain: light
            - domain: switch
            - domain: fan
            - domain: cover
    
    # Power Controls
    use_power_buttons:
      name: Enable Power Buttons (ON/OFF)
      description: Use ON/OFF buttons to control devices
      selector:
        boolean:
      default: true
    
    # Brightness Controls
    use_brightness_buttons:
      name: Enable Brightness Buttons
      description: |
        Use brightness up/down buttons.
        Short press: Step brightness
        Long press: Set to min/max
      selector:
        boolean:
      default: true
    
    brightness_step:
      name: Brightness Step Percentage
      description: How much to change brightness on short press
      selector:
        number:
          min: 5
          max: 50
          step: 5
          unit_of_measurement: "%"
      default: 10
    
    # Color Controls
    use_color_buttons:
      name: Enable Color Buttons
      description: |
        Use color buttons (red, green, blue, cycle).
        Short press: Set color
        Long press: Set color at full brightness
      selector:
        boolean:
      default: true
    
    # Color Temperature Controls
    use_temperature_buttons:
      name: Enable Color Temperature Buttons
      description: |
        Use warm/cold buttons for color temperature.
        Short press: Step temperature
        Long press: Set to warmest/coldest
      selector:
        boolean:
      default: true
    
    temperature_step:
      name: Color Temperature Step (Mireds)
      description: How much to change color temperature on short press
      selector:
        number:
          min: 10
          max: 100
          step: 10
          unit_of_measurement: "mireds"
      default: 50
    
    # Scene Controls
    use_scene_buttons:
      name: Enable Scene Buttons (Heart 1/2)
      description: Use heart buttons to activate scenes
      selector:
        boolean:
      default: false
    
    scene_1:
      name: Scene 1 (Heart 1)
      description: Scene to activate with Heart 1 button (optional)
      selector:
        entity:
          domain: scene
      default: ""
    
    scene_2:
      name: Scene 2 (Heart 2)
      description: Scene to activate with Heart 2 button (optional)
      selector:
        entity:
          domain: scene
      default: ""
    
    # Custom Actions
    use_custom_refresh:
      name: Enable Custom Refresh Actions
      description: |
        Override default refresh button behavior.
        Short press: Toggle devices
        Long press: Custom action (optional)
      selector:
        boolean:
      default: false
    
    refresh_long_action:
      name: Refresh Long Press Action (Optional)
      description: |
        Custom action for long press on refresh button.
        Leave empty to use default (toggle).
      selector:
        action:
      default: []

mode: restart
max_exceeded: silent

variables:
  bank_var: !input bank
  brightness_step_var: !input brightness_step
  temperature_step_var: !input temperature_step
  use_power_var: !input use_power_buttons
  use_brightness_var: !input use_brightness_buttons
  use_color_var: !input use_color_buttons
  use_temperature_var: !input use_temperature_buttons
  use_scene_var: !input use_scene_buttons
  use_custom_refresh_var: !input use_custom_refresh
  scene_1_var: !input scene_1
  scene_2_var: !input scene_2
  refresh_action_var: !input refresh_long_action

trigger:
  # Power Controls - ON
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "turn_on_{{ bank_var }}"
    id: "on"
  
  # Power Controls - OFF
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "turn_off_{{ bank_var }}"
    id: "off"
  
  # Brightness Controls - Dim UP
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "dim_up_{{ bank_var }}"
    id: "brightness_up_short"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "dim_up_{{ bank_var }}"
    id: "brightness_max"
  
  # Brightness Controls - Dim DOWN
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "dim_down_{{ bank_var }}"
    id: "brightness_down_short"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "dim_down_{{ bank_var }}"
    id: "brightness_min"
  
  # Color Controls - Red
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "red_{{ bank_var }}"
    id: "color_red"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "red_{{ bank_var }}"
    id: "color_red_long"
  
  # Color Controls - Green
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "green_{{ bank_var }}"
    id: "color_green"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "green_{{ bank_var }}"
    id: "color_green_long"
  
  # Color Controls - Blue
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "blue_{{ bank_var }}"
    id: "color_blue"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "blue_{{ bank_var }}"
    id: "color_blue_long"
  
  # Color Controls - Cycle
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "cycle_{{ bank_var }}"
    id: "color_cycle"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "cycle_{{ bank_var }}"
    id: "color_cycle_long"
  
  # Color Temperature - Warm
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "warm_{{ bank_var }}"
    id: "temp_warm_short"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "warm_{{ bank_var }}"
    id: "temp_warm_max"
  
  # Color Temperature - Cold
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "cold_{{ bank_var }}"
    id: "temp_cold_short"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "cold_{{ bank_var }}"
    id: "temp_cold_max"
  
  # Scene Controls
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "heart_1_{{ bank_var }}"
    id: "scene_1"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "heart_2_{{ bank_var }}"
    id: "scene_2"
  
  # Refresh button
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: "refresh_{{ bank_var }}"
    id: "refresh_short"
  
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: "refresh_{{ bank_var }}"
    id: "refresh_long"

action:
  - choose:
      # Power ON
      - conditions:
          - condition: trigger
            id: "on"
          - "{{ use_power_var }}"
        sequence:
          - service: homeassistant.turn_on
            target: !input target_lights
      
      # Power OFF
      - conditions:
          - condition: trigger
            id: "off"
          - "{{ use_power_var }}"
        sequence:
          - service: homeassistant.turn_off
            target: !input target_lights
      
      # Brightness UP (short press - step)
      - conditions:
          - condition: trigger
            id: "brightness_up_short"
          - "{{ use_brightness_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              brightness_step_pct: "{{ brightness_step_var }}"
      
      # Brightness UP (long press - max)
      - conditions:
          - condition: trigger
            id: "brightness_max"
          - "{{ use_brightness_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              brightness_pct: 100
      
      # Brightness DOWN (short press - step)
      - conditions:
          - condition: trigger
            id: "brightness_down_short"
          - "{{ use_brightness_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              brightness_step_pct: "{{ -brightness_step_var }}"
      
      # Brightness DOWN (long press - min)
      - conditions:
          - condition: trigger
            id: "brightness_min"
          - "{{ use_brightness_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              brightness_pct: 1
      
      # Color Red (short press)
      - conditions:
          - condition: trigger
            id: "color_red"
          - "{{ use_color_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              rgb_color: [255, 0, 0]
      
      # Color Red (long press - full brightness)
      - conditions:
          - condition: trigger
            id: "color_red_long"
          - "{{ use_color_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              hs_color: [0, 100]
              brightness_pct: 100
      
      # Color Green (short press)
      - conditions:
          - condition: trigger
            id: "color_green"
          - "{{ use_color_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              rgb_color: [0, 255, 0]
      
      # Color Green (long press - full brightness)
      - conditions:
          - condition: trigger
            id: "color_green_long"
          - "{{ use_color_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              hs_color: [120, 100]
              brightness_pct: 100
      
      # Color Blue (short press)
      - conditions:
          - condition: trigger
            id: "color_blue"
          - "{{ use_color_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              rgb_color: [0, 0, 255]
      
      # Color Blue (long press - full brightness)
      - conditions:
          - condition: trigger
            id: "color_blue_long"
          - "{{ use_color_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              hs_color: [240, 100]
              brightness_pct: 100
      
      # Color Cycle (short press - enable colorloop)
      - conditions:
          - condition: trigger
            id: "color_cycle"
          - "{{ use_color_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              effect: "colorloop"
      
      # Color Cycle (long press - stop effect)
      - conditions:
          - condition: trigger
            id: "color_cycle_long"
          - "{{ use_color_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              effect: "none"
      
      # Color Temperature Warm (short press - step warmer)
      - conditions:
          - condition: trigger
            id: "temp_warm_short"
          - "{{ use_temperature_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              color_temp: >
                {% set lights = expand(target_lights.entity_id) | selectattr('domain', 'eq', 'light') | list %}
                {% if lights | length > 0 %}
                  {{ (state_attr(lights[0].entity_id, 'color_temp') | int(250)) + temperature_step_var }}
                {% else %}
                  {{ 250 + temperature_step_var }}
                {% endif %}
      
      # Color Temperature Warm (long press - warmest)
      - conditions:
          - condition: trigger
            id: "temp_warm_max"
          - "{{ use_temperature_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              color_temp: 454
      
      # Color Temperature Cold (short press - step colder)
      - conditions:
          - condition: trigger
            id: "temp_cold_short"
          - "{{ use_temperature_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              color_temp: >
                {% set lights = expand(target_lights.entity_id) | selectattr('domain', 'eq', 'light') | list %}
                {% if lights | length > 0 %}
                  {{ (state_attr(lights[0].entity_id, 'color_temp') | int(250)) - temperature_step_var }}
                {% else %}
                  {{ 250 - temperature_step_var }}
                {% endif %}
      
      # Color Temperature Cold (long press - coldest)
      - conditions:
          - condition: trigger
            id: "temp_cold_max"
          - "{{ use_temperature_var }}"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              color_temp: 153
      
      # Scene 1 (Heart 1)
      - conditions:
          - condition: trigger
            id: "scene_1"
          - "{{ use_scene_var and scene_1_var != '' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: "{{ scene_1_var }}"
      
      # Scene 2 (Heart 2)
      - conditions:
          - condition: trigger
            id: "scene_2"
          - "{{ use_scene_var and scene_2_var != '' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: "{{ scene_2_var }}"
      
      # Refresh short (toggle all devices)
      - conditions:
          - condition: trigger
            id: "refresh_short"
        sequence:
          - service: homeassistant.toggle
            target: !input target_lights
      
      # Refresh long (custom action or update entities)
      - conditions:
          - condition: trigger
            id: "refresh_long"
        sequence:
          - choose:
              # If custom action provided, use it
              - conditions: "{{ use_custom_refresh_var and refresh_action_var | length > 0 }}"
                sequence: !input refresh_long_action
            # Otherwise, update entity states
            default:
              - service: homeassistant.update_entity
                target: !input target_lights
