blueprint:
  name: Eglo Remote 2.0 (AwoX) - Basic Light Control
  description: >
    Control lights with the Eglo Remote 2.0 (AwoX ERCU_3groups_Zm).
    Includes on/off, brightness, and basic color/temperature control.
  domain: automation
  input:
    remote:
      name: Eglo Remote 2.0
      description: The AwoX ERCU_3groups_Zm remote to use
      selector:
        device:
          integration: zha
          manufacturer: AwoX
          model: ERCU_3groups_Zm
    target_light:
      name: Target Light(s)
      description: The light(s) or light group to control
      selector:
        target:
          entity:
            domain: light
    brightness_step:
      name: Brightness Step
      description: Percentage to change brightness with each dim button press
      default: 10
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: "%"

mode: restart
max_exceeded: silent

trigger:
  # Power Control
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: turn_on
    id: "turn_on"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: turn_off
    id: "turn_off"
  
  # Brightness Control
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: dim_up
    id: "brightness_up_short"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_up
    id: "brightness_max"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: dim_down
    id: "brightness_down_short"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_down
    id: "brightness_min"
  
  # Color Control
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: red
    id: "color_red"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: green
    id: "color_green"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: blue
    id: "color_blue"
  
  # Color Temperature
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: warm
    id: "color_temp_warm"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: cold
    id: "color_temp_cold"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: warm
    id: "color_temp_warmest"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: cold
    id: "color_temp_coldest"

action:
  - choose:
      # Power Control
      - conditions:
          - condition: trigger
            id: "turn_on"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 100
      
      - conditions:
          - condition: trigger
            id: "turn_off"
        sequence:
          - service: light.turn_off
            target: !input target_light
      
      # Brightness Control
      - conditions:
          - condition: trigger
            id: "brightness_up_short"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: !input brightness_step
      
      - conditions:
          - condition: trigger
            id: "brightness_down_short"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: "{{ -(brightness_step | int) }}"
      
      - conditions:
          - condition: trigger
            id: "brightness_max"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 100
      
      - conditions:
          - condition: trigger
            id: "brightness_min"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 1
      
      # Color Control
      - conditions:
          - condition: trigger
            id: "color_red"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              rgb_color: [255, 0, 0]
      
      - conditions:
          - condition: trigger
            id: "color_green"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              rgb_color: [0, 255, 0]
      
      - conditions:
          - condition: trigger
            id: "color_blue"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              rgb_color: [0, 0, 255]
      
      # Color Temperature Control
      - conditions:
          - condition: trigger
            id: "color_temp_warm"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              color_temp: "{{ state_attr(target_light.entity_id, 'color_temp') | int + 20 }}"
      
      - conditions:
          - condition: trigger
            id: "color_temp_cold"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              color_temp: "{{ state_attr(target_light.entity_id, 'color_temp') | int - 20 }}"
      
      - conditions:
          - condition: trigger
            id: "color_temp_warmest"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              color_temp: 454
      
      - conditions:
          - condition: trigger
            id: "color_temp_coldest"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              color_temp: 153
