blueprint:
  name: Eglo/AwoX Remote 3-Bank Control (ZHA)
  description: >
    Control lights with the Eglo/AwoX ERCU_3groups_Zm remote using its 3-bank functionality.
    
    **Important**: This remote has 3 banks. Create 3 separate automations (one for each bank).
    Press buttons 1/2/3 on the remote to switch between banks.
    
    Includes on/off, brightness, colors, temperature, scenes, and refresh controls.
    
    **No Touchlink or ZHA groups needed!** The blueprint handles everything in Home Assistant.
  domain: automation
  input:
    remote:
      name: Eglo Remote 2.0
      description: The AwoX ERCU_3groups_Zm remote to use
      selector:
        device:
          integration: zha
          manufacturer: AwoX
          model: ERCU_3groups_Zm
    
    bank:
      name: Bank Number
      description: |
        Which bank to control (1, 2, or 3).
        Press button 1/2/3 on the remote to switch to this bank.
        Create 3 separate automations to use all banks.
      selector:
        select:
          options:
            - label: "Bank 1"
              value: "1"
            - label: "Bank 2"
              value: "2"
            - label: "Bank 3"
              value: "3"
      default: "1"
    
    target_light:
      name: Target Light(s)
      description: The light(s) or light group to control with this bank
      selector:
        target:
          entity:
            domain: light
    
    brightness_step:
      name: Brightness Step
      description: Percentage to change brightness with each dim button press
      default: 10
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: "%"

mode: restart
max_exceeded: silent

variables:
  bank_var: !input bank

trigger:
  # Power Control - Bank 1
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: turn_on_1
    id: "turn_on"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: turn_off_1
    id: "turn_off"
    enabled: "{{ bank_var == '1' }}"
  
  # Power Control - Bank 2
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: turn_on_2
    id: "turn_on"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: turn_off_2
    id: "turn_off"
    enabled: "{{ bank_var == '2' }}"
  
  # Power Control - Bank 3
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: turn_on_3
    id: "turn_on"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: turn_off_3
    id: "turn_off"
    enabled: "{{ bank_var == '3' }}"
  
  # Brightness Control - Bank 1
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: dim_up_1
    id: "brightness_up_short"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_up_1
    id: "brightness_max"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: dim_down_1
    id: "brightness_down_short"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_down_1
    id: "brightness_min"
    enabled: "{{ bank_var == '1' }}"
  
  # Brightness Control - Bank 2
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: dim_up_2
    id: "brightness_up_short"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_up_2
    id: "brightness_max"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: dim_down_2
    id: "brightness_down_short"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_down_2
    id: "brightness_min"
    enabled: "{{ bank_var == '2' }}"
  
  # Brightness Control - Bank 3
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: dim_up_3
    id: "brightness_up_short"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_up_3
    id: "brightness_max"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: dim_down_3
    id: "brightness_down_short"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: dim_down_3
    id: "brightness_min"
    enabled: "{{ bank_var == '3' }}"
  
  # Color Control - Bank 1
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: red_1
    id: "color_red"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: green_1
    id: "color_green"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: blue_1
    id: "color_blue"
    enabled: "{{ bank_var == '1' }}"
  
  # Color Control - Bank 2
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: red_2
    id: "color_red"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: green_2
    id: "color_green"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: blue_2
    id: "color_blue"
    enabled: "{{ bank_var == '2' }}"
  
  # Color Control - Bank 3
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: red_3
    id: "color_red"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: green_3
    id: "color_green"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: blue_3
    id: "color_blue"
    enabled: "{{ bank_var == '3' }}"
  
  # Color Temperature - Bank 1
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: warm_1
    id: "color_temp_warm"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: cold_1
    id: "color_temp_cold"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: warm_1
    id: "color_temp_warmest"
    enabled: "{{ bank_var == '1' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: cold_1
    id: "color_temp_coldest"
    enabled: "{{ bank_var == '1' }}"
  
  # Color Temperature - Bank 2
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: warm_2
    id: "color_temp_warm"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: cold_2
    id: "color_temp_cold"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: warm_2
    id: "color_temp_warmest"
    enabled: "{{ bank_var == '2' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: cold_2
    id: "color_temp_coldest"
    enabled: "{{ bank_var == '2' }}"
  
  # Color Temperature - Bank 3
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: warm_3
    id: "color_temp_warm"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_short_press
    subtype: cold_3
    id: "color_temp_cold"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: warm_3
    id: "color_temp_warmest"
    enabled: "{{ bank_var == '3' }}"
  - platform: device
    domain: zha
    device_id: !input remote
    type: remote_button_long_press
    subtype: cold_3
    id: "color_temp_coldest"
    enabled: "{{ bank_var == '3' }}"

action:
  - choose:
      # Power Control
      - conditions:
          - condition: trigger
            id: "turn_on"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 100
      
      - conditions:
          - condition: trigger
            id: "turn_off"
        sequence:
          - service: light.turn_off
            target: !input target_light
      
      # Brightness Control
      - conditions:
          - condition: trigger
            id: "brightness_up_short"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: !input brightness_step
      
      - conditions:
          - condition: trigger
            id: "brightness_down_short"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: "{{ -(brightness_step | int) }}"
      
      - conditions:
          - condition: trigger
            id: "brightness_max"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 100
      
      - conditions:
          - condition: trigger
            id: "brightness_min"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: 1
      
      # Color Control
      - conditions:
          - condition: trigger
            id: "color_red"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              rgb_color: [255, 0, 0]
      
      - conditions:
          - condition: trigger
            id: "color_green"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              rgb_color: [0, 255, 0]
      
      - conditions:
          - condition: trigger
            id: "color_blue"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              rgb_color: [0, 0, 255]
      
      # Color Temperature Control
      - conditions:
          - condition: trigger
            id: "color_temp_warm"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              kelvin: 3000  # Warm white
      
      - conditions:
          - condition: trigger
            id: "color_temp_cold"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              kelvin: 5000  # Cool white
      
      - conditions:
          - condition: trigger
            id: "color_temp_warmest"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              kelvin: 2200  # Warmest (matches 454 mireds)
      
      - conditions:
          - condition: trigger
            id: "color_temp_coldest"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              kelvin: 6536  # Coldest (matches 153 mireds)
